### ISSUE TITLE
Cannot mix tz-aware with tz-naive values

### ISSUE THREAD

**Issue by phelps-sg** [phelps-sg/zipline-tardis-bundle#3]
~~~
  winsorise_uint32(raw_data, invalid_data_behavior, "volume", *OHLC)
Traceback (most recent call last):
  File "/home/sphelps/mambaforge/envs/zipline-tardis-bundle/bin/zipline", line 11, in <module>
    sys.exit(main())
  File "/home/sphelps/mambaforge/envs/zipline-tardis-bundle/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/sphelps/mambaforge/envs/zipline-tardis-bundle/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/sphelps/mambaforge/envs/zipline-tardis-bundle/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sphelps/mambaforge/envs/zipline-tardis-bundle/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sphelps/mambaforge/envs/zipline-tardis-bundle/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/sphelps/mambaforge/envs/zipline-tardis-bundle/lib/python3.10/site-packages/zipline/__main__.py", line 397, in ingest
    bundles_module.ingest(
  File "/home/sphelps/mambaforge/envs/zipline-tardis-bundle/lib/python3.10/site-packages/zipline/data/bundles/core.py", line 445, in ingest
    bundle.ingest(
  File "/home/sphelps/vcs/coding/zipline-tardis-bundle/zipline_tardis_bundle/bundle.py", line 139, in ingest
    tardis_bundle(
  File "/home/sphelps/vcs/coding/zipline-tardis-bundle/zipline_tardis_bundle/bundle.py", line 213, in tardis_bundle
    asset_db_writer.write(equities=metadata_df)
  File "/home/sphelps/mambaforge/envs/zipline-tardis-bundle/lib/python3.10/site-packages/zipline/assets/asset_writer.py", line 800, in write
    data = self._load_data(
  File "/home/sphelps/mambaforge/envs/zipline-tardis-bundle/lib/python3.10/site-packages/zipline/assets/asset_writer.py", line 1019, in _load_data
    equities_output, equities_mappings = self._normalize_equities(
  File "/home/sphelps/mambaforge/envs/zipline-tardis-bundle/lib/python3.10/site-packages/zipline/assets/asset_writer.py", line 955, in _normalize_equities
    equities_output[col] = _dt_to_epoch_ns(equities_output[col])
  File "/home/sphelps/mambaforge/envs/zipline-tardis-bundle/lib/python3.10/site-packages/zipline/assets/asset_writer.py", line 401, in _dt_to_epoch_ns
    index = pd.to_datetime(dt_series.values)
  File "/home/sphelps/mambaforge/envs/zipline-tardis-bundle/lib/python3.10/site-packages/pandas/core/tools/datetimes.py", line 1131, in to_datetime
    cache_array = _maybe_cache(argc, format, cache, convert_listlike)
  File "/home/sphelps/mambaforge/envs/zipline-tardis-bundle/lib/python3.10/site-packages/pandas/core/tools/datetimes.py", line 254, in _maybe_cache
    cache_dates = convert_listlike(unique_dates, format)
  File "/home/sphelps/mambaforge/envs/zipline-tardis-bundle/lib/python3.10/site-packages/pandas/core/tools/datetimes.py", line 490, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/home/sphelps/mambaforge/envs/zipline-tardis-bundle/lib/python3.10/site-packages/pandas/core/arrays/datetimes.py", line 2346, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "tslib.pyx", line 403, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 552, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 480, in pandas._libs.tslib.array_to_datetime
  File "conversion.pyx", line 723, in pandas._libs.tslibs.conversion.convert_timezone
ValueError: Cannot mix tz-aware with tz-naive values, at position 1

~~~

**Comment by phelps-sg** [comment]
This occurs when there are tardis files present for the asset but they do not contain any data.  The bundle now raises an informative exception when this happens.  The solution is to omit the offending assets from the bundle specification in extension.py.
